# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_choice', '0002_auto_20160722_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'universities'},
        ),
        migrations.AddField(
            model_name='accommodation',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catering',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drink',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gymmembership',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='haircut',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hometrip',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postnightmeal',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roundsforfriend',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopping',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxi',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
